"""Savage Doctor: phone bootstrap, setup, diagnostics and SAFE repair.

Boundary: Doctor only repairs application-level state beneath SAVAGE_AI_ROOT. It never formats,
mounts, resizes or repairs storage, touches block devices, SELinux, boot settings, firewalls or
network ports, escalates privileges, downloads anything, or runs target-affecting actions.
Every repair is an Action marked safe; --yes approves only safe actions.
(Future: 'Build llama.cpp?' / 'Download recommended model?' will be added as separate
explicitly-approved stages; nothing is downloaded in this milestone.)
"""
import hashlib, json, logging, os, shlex, shutil, subprocess, sys, tempfile, time, uuid
from logging.handlers import RotatingFileHandler

from . import __version__, core, memory as memmod
from .agents import agent_list, registry_problem, write_registry
from .commander import Commander
from .config import Config, DEFAULTS, PHONE_ROOT
from .permissions import Perm, PermissionDenied, check as perm_check
from .providers import LlamaCppProvider
from .skills import Registry

PASS, ACTION, FAIL, OPTIONAL = "PASS", "ACTION", "FAIL", "OPTIONAL"
DIRS = ["models", "agents", "memory", "skills", "knowledge", "projects", "engagements",
        "logs", "config", "backups", "bin", "src", "tmp"]
MIN_FREE_BYTES = 512 * 2**20
OK_FREE_BYTES = 5 * 2**30
MAX_OUT = 2000
SYMS = {PASS: ("✓", "OK"), ACTION: ("!", "!"), "FIXING": ("→", ">"), FAIL: ("✗", "X"), OPTIONAL: ("-", "-")}
NOT_MOUNTED = ("SAVAGE AI STORAGE NOT MOUNTED\n"
               "  {root} is {why}.\n"
               "  The existing Savage AI filesystem must be mounted there before setup can continue.\n"
               "  Savage AI will not install onto internal storage, and never formats, mounts or repairs it.")


class Check:
    def __init__(self, state, detail="", prompt=None, fixing=None, fix=None, done=None, safe=True):
        self.state, self.detail, self.prompt = state, detail, prompt
        self.fixing, self.fix, self.done, self.safe = fixing, fix, done, safe


# ---------- shared helpers (also used by bootstrap) ----------
def is_mount_point(path):
    return os.path.ismount(os.path.realpath(path))


def storage_problem(cfg):
    """Return banner text if a required mount is missing, else None."""
    if not cfg.require_mount:
        return None
    if not os.path.isdir(cfg.root):
        why = "missing"
    elif not is_mount_point(cfg.root):
        why = "not a mounted filesystem (plain directory)"
    else:
        return None
    return NOT_MOUNTED.format(root=cfg.root, why=why)


def can_write(path):
    try:
        fd, name = tempfile.mkstemp(dir=path, prefix=".savage-w-")
        os.close(fd)
        os.unlink(name)
        return True
    except OSError:
        return False


def nearest_existing(path):
    while path and not os.path.exists(path):
        parent = os.path.dirname(path)
        if parent == path:
            break
        path = parent
    return path


def package_dir():
    return os.path.dirname(os.path.abspath(__file__))


def source_candidates(cfg, state_source=None):
    inst = os.path.realpath(cfg.path("src"))
    for c in (cfg.env.get("SAVAGE_SOURCE_DIR"), state_source, os.path.dirname(package_dir())):
        if c and os.path.isfile(os.path.join(c, "savage", "__init__.py")) and os.path.realpath(c) != inst:
            return os.path.abspath(c)
    return None


def tree_hash(pkg):
    h = hashlib.sha256()
    for dp, dn, fn in os.walk(pkg):
        dn[:] = sorted(d for d in dn if d != "__pycache__")
        for f in sorted(fn):
            if f.endswith(".py"):
                p = os.path.join(dp, f)
                h.update(os.path.relpath(p, pkg).encode())
                with open(p, "rb") as fh:
                    h.update(fh.read())
    return h.hexdigest()


def install_app(cfg, source_dir):
    """Copy the savage package into $ROOT/src (swap in place; app-owned code only)."""
    src = os.path.join(source_dir, "savage")
    dst_dir = cfg.path("src")
    os.makedirs(dst_dir, exist_ok=True)
    dst, new, old = (os.path.join(dst_dir, n) for n in ("savage", ".savage.new", ".savage.old"))
    if os.path.realpath(src) == os.path.realpath(dst):
        return
    for p in (new, old):
        shutil.rmtree(p, ignore_errors=True)
    shutil.copytree(src, new, ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))
    if os.path.exists(dst):
        os.rename(dst, old)
    os.rename(new, dst)
    shutil.rmtree(old, ignore_errors=True)


def shell_path(prefix=None):
    for p in ((os.path.join(prefix, "bin", "sh") if prefix else None), "/system/bin/sh", "/bin/sh"):
        if p and os.path.exists(p):
            return p
    return "/bin/sh"


def launcher_text(cfg, source_dir=None, prefix=None):
    q = shlex.quote
    lines = [f"#!{shell_path(prefix)}", "# Generated by 'savage doctor'. Safe to regenerate.",
             f'[ -n "${{SAVAGE_AI_ROOT:-}}" ] || SAVAGE_AI_ROOT={q(cfg.root)}', "export SAVAGE_AI_ROOT"]
    if source_dir:
        lines += [f'[ -n "${{SAVAGE_SOURCE_DIR:-}}" ] || SAVAGE_SOURCE_DIR={q(source_dir)}', "export SAVAGE_SOURCE_DIR"]
    lines += ['PYTHONPATH="$SAVAGE_AI_ROOT/src${PYTHONPATH:+:$PYTHONPATH}"', "export PYTHONPATH",
              'PY="$SAVAGE_AI_ROOT/venv/bin/python"', '[ -x "$PY" ] || PY=python3',
              'exec "$PY" -m savage "$@"', ""]
    return "\n".join(lines)


def launcher_targets(cfg, prefix=None):
    t = [cfg.path("bin", "savage")]
    if prefix and os.path.isdir(os.path.join(prefix, "bin")):
        t.append(os.path.join(prefix, "bin", "savage"))
    return t


def write_launchers(cfg, source_dir=None, prefix=None):
    text, done = launcher_text(cfg, source_dir, prefix), []
    for t in launcher_targets(cfg, prefix):
        try:
            os.makedirs(os.path.dirname(t), exist_ok=True)
            tmp = t + ".new"
            with open(tmp, "w") as f:
                f.write(text)
            os.chmod(tmp, 0o755)
            os.replace(tmp, t)
            done.append(t)
        except OSError:
            if t == cfg.path("bin", "savage"):
                raise  # the root launcher is mandatory; $PREFIX one is best-effort
    return done


def launcher_ok(cfg, source_dir=None, prefix=None):
    text = launcher_text(cfg, source_dir, prefix)
    missing = []
    for t in launcher_targets(cfg, prefix):
        try:
            with open(t) as f:
                good = f.read() == text and os.access(t, os.X_OK)
        except OSError:
            good = False
        if not good:
            missing.append(t)
    return missing


def venv_python(cfg):
    return cfg.path("venv", "bin", "python")


def run_py(cfg, code, readonly=False):
    py = venv_python(cfg)
    py = py if os.path.isfile(py) else sys.executable
    env = dict(os.environ, PYTHONPATH=cfg.path("src"), SAVAGE_AI_ROOT=cfg.root)
    if readonly:
        env["PYTHONDONTWRITEBYTECODE"] = "1"
    try:
        p = subprocess.run([py, "-c", code], capture_output=True, text=True, timeout=30, env=env)
        return p.returncode, (p.stdout + p.stderr).strip()[:MAX_OUT]
    except (OSError, subprocess.TimeoutExpired) as e:
        return 1, e.__class__.__name__


class State:
    """install-state.json: a progress hint only. Doctor always re-verifies real state."""

    def __init__(self, cfg):
        self.path = cfg.path("config", "install-state.json")
        self.data = {"schema": 1, "stages": {}}
        try:
            with open(self.path) as f:
                d = json.load(f)
            if isinstance(d, dict) and isinstance(d.get("stages"), dict):
                self.data = d
        except (OSError, ValueError):
            pass

    def done(self, k):
        return k in self.data["stages"]

    def mark(self, k):
        self.data["stages"][k] = {"verified": int(time.time()), "version": __version__}

    def drop(self, k):
        self.data["stages"].pop(k, None)

    def save(self):
        self.data["updated"] = int(time.time())
        self.data["app_version"] = __version__
        tmp = self.path + ".new"
        with open(tmp, "w") as f:
            json.dump(self.data, f, indent=2)
        os.replace(tmp, self.path)


class Doctor:
    def __init__(self, cfg, check=False, yes=False, verbose=False, inp=input, out=None, prefix=None):
        self.cfg, self.check, self.yes, self.verbose = cfg, check, yes, verbose
        self.inp, self.out, self.prefix = inp, out or sys.stdout, prefix
        self.results, self.pending, self.logger, self.state = [], [], None, None
        self.fatal = False
        enc = getattr(self.out, "encoding", None) or "ascii"
        try:
            "✓→✗".encode(enc)
            self.u = 0
        except (UnicodeError, LookupError):
            self.u = 1

    # ----- output/log -----
    def p(self, s="", end="\n"):
        print(s, file=self.out, end=end)
        self.log(s)

    def log(self, s):
        s = str(s).strip()
        if not s or self.check:
            return
        if self.logger:
            self.logger.info(s)
        else:
            self.pending.append(s)

    def attach_log(self):
        if self.check or self.logger or not os.path.isdir(self.cfg.path("logs")):
            return
        lg = logging.getLogger("savage.doctor." + uuid.uuid4().hex[:6])
        lg.setLevel(logging.INFO)
        lg.propagate = False
        try:
            h = RotatingFileHandler(self.cfg.path("logs", "doctor.log"), maxBytes=128 * 1024, backupCount=1)
            h.setFormatter(logging.Formatter("%(asctime)s %(message)s"))
            lg.addHandler(h)
        except OSError:
            return
        self.logger = lg
        lg.info("=== doctor run %s check=%s yes=%s ===", __version__, self.check, self.yes)
        for s in self.pending:
            lg.info(s)
        self.pending = []

    def line(self, state, text):
        self.p(f"[{SYMS[state][self.u]}] {text}")

    def v(self, text):
        if self.verbose:
            self.p("      " + text)

    def confirm(self, prompt, safe=True):
        if self.yes and safe:
            self.p(f"    {prompt} [Y/n] y (--yes)")
            return True
        if self.yes:
            self.p("    This action is not 'safe'; --yes does not approve it.")
        try:
            ans = self.inp(f"    {prompt} [Y/n] ")
        except EOFError:
            self.p("    (no input; skipped. Use --yes to approve SAFE repairs)")
            return False
        self.log(f"answer: {ans!r}")
        return ans.strip().lower() in ("", "y", "yes")

    # ----- stage runner -----
    def stage(self, key, label, fn, optional_row=None):
        try:
            c = fn()
        except Exception as e:
            c = Check(FAIL, f"internal error: {e.__class__.__name__}: {e}")
        if c.state == ACTION:
            self.line(ACTION, f"{label}: {c.detail}")
            if self.check:
                self.finish(key, label, c)
                return c
            if self.confirm(c.prompt, c.safe):
                self.line("FIXING", c.fixing or "Fixing...")
                done = c.done
                try:
                    c.fix()
                except Exception as e:
                    c = Check(FAIL, f"repair failed: {e.__class__.__name__}: {e}")
                else:
                    c = fn()
                    if c.state == PASS:
                        c.detail = done or c.detail
                        self.line(PASS, f"{label}: {c.detail}")
                        return self.finish(key, label, c)
            else:
                c = Check(ACTION, "declined/skipped")
            self.line(c.state, f"{label}: {c.detail}")
        else:
            self.line(c.state, f"{label}: {c.detail}")
        return self.finish(key, label, c)

    def finish(self, key, label, c):
        self.results.append((key, label, c.state, c.detail))
        if self.state and not self.check:
            if c.state == PASS:
                self.state.mark(key)
            else:
                if self.state.done(key):
                    self.v("state file said done, but verification failed; ignoring it")
                self.state.drop(key)
            self.save_state()
        return c

    def save_state(self):
        if self.state and os.path.isdir(self.cfg.path("config")):
            try:
                self.state.save()
            except OSError:
                pass

    def res(self, key):
        return next((s for k, _, s, _ in self.results if k == key), None)

    # ----- stage 1 -----
    def c_platform(self):
        cfg, bad = self.cfg, False
        m = core.meminfo()
        free = shutil.disk_usage(nearest_existing(cfg.root)).free
        pyok = sys.version_info >= (3, 8)
        cc = next((c for c in ("clang", "gcc", "cc") if shutil.which(c)), None)
        rows = [
            ("Android", PASS if core.is_android() else OPTIONAL, "yes" if core.is_android() else "no (development host)"),
            ("Termux", PASS if core.is_termux() else OPTIONAL, "yes" if core.is_termux() else "no"),
            ("Arch", PASS if os.uname().machine in ("aarch64", "arm64") else OPTIONAL, os.uname().machine),
            ("Python", PASS if pyok else FAIL, sys.version.split()[0] + ("" if pyok else " (need >= 3.8)")),
            ("Git", PASS if shutil.which("git") else OPTIONAL, shutil.which("git") or "missing (pkg install git)"),
            ("Compiler", PASS if cc else OPTIONAL, cc or "missing (needed later for llama.cpp)"),
            ("CMake", PASS if shutil.which("cmake") else OPTIONAL, shutil.which("cmake") or "missing (needed later for llama.cpp)"),
            ("RAM", PASS if m.get("MemTotal", 0) >= 2500 else OPTIONAL,
             f"{m.get('MemTotal', '?')} MiB total, {m.get('MemAvailable', '?')} MiB free"),
            ("Swap", PASS if m.get("SwapTotal", 0) > 0 else OPTIONAL, f"{m.get('SwapTotal', 0)} MiB"),
            ("Disk", PASS if free >= MIN_FREE_BYTES else OPTIONAL, f"{free / 2**30:.1f} GiB free"),
        ]
        for n, s, d in rows:
            self.line(s, f"  {n}: {d}")
            bad = bad or s == FAIL
        return Check(FAIL if bad else PASS, "platform requirements" if bad else "usable")

    # ----- stage 2 -----
    def c_storage(self):
        cfg = self.cfg
        if core.is_android() and not cfg.explicit_root:
            self.fatal = True
            return Check(FAIL, f"SAVAGE_AI_ROOT is not set. Run: export SAVAGE_AI_ROOT={PHONE_ROOT}")
        prob = storage_problem(cfg)
        if prob:
            self.fatal = True
            self.p(prob)
            return Check(FAIL, "NOT MOUNTED")
        if not os.path.isdir(cfg.root):
            if os.path.exists(cfg.root):
                self.fatal = True
                return Check(FAIL, f"{cfg.root} exists but is not a directory")
            return Check(ACTION, f"{cfg.root} does not exist (development root)",
                         f"Create {cfg.root}?", "Creating development root...",
                         lambda: os.makedirs(cfg.root, exist_ok=True), "created")
        if not can_write(cfg.root):
            self.fatal = True
            return Check(FAIL, f"{cfg.root} is not writable by uid {os.getuid()}. Android may deny non-root "
                               "access; Savage will not change permissions. Fix access yourself or run once from a root shell.")
        if not core.check_exec(cfg.root):
            self.fatal = True
            return Check(FAIL, f"{cfg.root} does not allow executing files (noexec mount?)")
        free = shutil.disk_usage(cfg.root).free
        if free < MIN_FREE_BYTES:
            self.fatal = True
            return Check(FAIL, f"only {free / 2**20:.0f} MiB free")
        note = "" if free >= OK_FREE_BYTES else " (low for models)"
        mt = "mounted, " if cfg.require_mount else ""
        return Check(PASS, f"{cfg.root}: {mt}writable, executable, {free / 2**30:.1f} GiB free{note}")

    # ----- stage 3 -----
    def c_dirs(self):
        cfg = self.cfg
        for d in DIRS:
            if os.path.exists(cfg.path(d)) and not os.path.isdir(cfg.path(d)):
                self.fatal = True
                return Check(FAIL, f"{cfg.path(d)} exists but is not a directory (not touching it)")
        miss = [d for d in DIRS if not os.path.isdir(cfg.path(d))]
        if miss:
            return Check(ACTION, f"{len(miss)} missing: {', '.join(miss)}", "Create missing directories?",
                         "Creating directories...", lambda: [os.makedirs(cfg.path(d), exist_ok=True) for d in miss],
                         "directories ready")
        return Check(PASS, f"{len(DIRS)} directories present")

    # ----- stage 4 -----
    def c_python(self):
        cfg, py = self.cfg, venv_python(self.cfg)

        def create():
            import venv
            shutil.rmtree(cfg.path("venv"), ignore_errors=True)  # application-owned, rebuildable
            venv.EnvBuilder(with_pip=False, symlinks=os.name != "nt").create(cfg.path("venv"))

        if not os.path.isfile(py):
            return Check(ACTION, "Python environment missing (no packages needed; standard library only)",
                         "Create Python environment?", "Creating venv...", create, "environment ready")
        rc, out = run_py(cfg, "import sys, sqlite3; print(sys.version_info[0])", True)
        if rc != 0:
            return Check(ACTION, "Python environment broken", "Recreate Python environment?",
                         "Recreating venv...", create, "environment ready")
        return Check(PASS, "venv OK (sqlite3 available, no extra dependencies)")

    # ----- stage 5 -----
    def source(self):
        return source_candidates(self.cfg, self.state.data.get("source_dir") if self.state else None)

    def c_app(self):
        cfg, src = self.cfg, self.source()
        inst = cfg.path("src", "savage")
        fix = lambda: install_app(cfg, src)
        if not os.path.isfile(os.path.join(inst, "__init__.py")):
            if not src:
                return Check(FAIL, "not installed and no source found (set SAVAGE_SOURCE_DIR or run bootstrap)")
            return Check(ACTION, "Savage AI not installed", "Install Savage AI?", "Installing...", fix, "installed")
        rc, out = run_py(cfg, "import savage; print(savage.__version__)", self.check)
        if rc != 0:
            if not src:
                return Check(FAIL, f"installed copy fails to import and no source to reinstall from: {out[:120]}")
            return Check(ACTION, "installed copy fails to import", "Reinstall Savage AI?", "Reinstalling...", fix, "reinstalled")
        if src and tree_hash(os.path.join(src, "savage")) != tree_hash(inst):
            return Check(ACTION, "installed copy differs from source", "Update installed Savage AI?",
                         "Updating...", fix, "updated")
        if src and self.state and not self.check:
            self.state.data["source_dir"] = src
        return Check(PASS, f"Savage AI {out} installed and importable")

    # ----- stage 6 -----
    def c_launcher(self):
        cfg, src = self.cfg, self.source()
        miss = launcher_ok(cfg, src, self.prefix)
        if miss:
            return Check(ACTION, "launcher missing or outdated: " + ", ".join(miss), "Create/repair the `savage` launcher?",
                         "Writing launcher...", lambda: write_launchers(cfg, src, self.prefix), "launcher ready")
        d = "launcher OK"
        if not shutil.which("savage"):
            d += f"; add to PATH: export PATH={cfg.path('bin')}:$PATH"
        return Check(PASS, d)

    # ----- stage 7 -----
    def cfg_file(self):
        return self.cfg.config_file

    def cfg_problem(self):
        """(problem, raw dict) for config file."""
        try:
            with open(self.cfg_file()) as f:
                raw = json.load(f)
        except FileNotFoundError:
            return "missing", None
        except (OSError, ValueError):
            return "unreadable/invalid JSON", None
        if not isinstance(raw, dict):
            return "not a JSON object", None
        bad = [k for k, dv in DEFAULTS.items() if k in raw and (
            type(raw[k]) is not type(dv) or (isinstance(dv, int) and raw[k] <= 0))]
        return (f"invalid values: {', '.join(bad)}" if bad else None), raw

    def c_config(self):
        cfg = self.cfg
        prob, raw = self.cfg_problem()

        def write(merged):
            os.makedirs(os.path.dirname(self.cfg_file()), exist_ok=True)
            tmp = self.cfg_file() + ".new"
            with open(tmp, "w") as f:
                json.dump(merged, f, indent=2)
            os.chmod(tmp, 0o600)
            os.replace(tmp, self.cfg_file())

        def fix_new():
            write(cfg.default_file_dict())

        def fix_bad():
            os.makedirs(cfg.path("backups"), exist_ok=True)
            if os.path.exists(self.cfg_file()):
                shutil.copy2(self.cfg_file(), cfg.path("backups", f"savage.json.{int(time.time())}.bak"))
            merged = cfg.default_file_dict()
            for k, v in (raw or {}).items():
                if k not in DEFAULTS or (type(v) is type(DEFAULTS[k]) and (not isinstance(v, int) or v > 0)):
                    merged[k] = v
            write(merged)

        if prob == "missing":
            return Check(ACTION, "configuration missing", "Create default configuration?",
                         "Writing config...", fix_new, "configuration created")
        if prob:
            return Check(ACTION, f"configuration {prob}", "Back up the file and repair it?",
                         "Repairing config (backup kept)...", fix_bad, "configuration repaired")
        for k in DEFAULTS:
            self.v(f"{k} = {cfg.get(k)!r}")
        return Check(PASS, "configuration valid")

    # ----- stage 8 -----
    def c_memory(self):
        cfg, path = self.cfg, self.cfg.path("memory", "savage.db")
        info = memmod.inspect(path)

        def fix_new():
            os.makedirs(os.path.dirname(path), exist_ok=True)
            memmod.Memory(cfg).close()

        def fix_old():
            os.makedirs(cfg.path("backups"), exist_ok=True)
            shutil.copy2(path, cfg.path("backups", f"savage.db.{int(time.time())}.bak"))
            m = memmod.Memory(cfg)
            try:
                m.repair_schema()
            finally:
                m.close()

        if not info["exists"]:
            return Check(ACTION, "SQLite database missing", "Create Savage Memory database?",
                         "Initializing memory...", fix_new, "Memory ready")
        if "error" in info:
            return Check(FAIL, f"database unreadable ({info['error'][:80]}); not touching it - restore from backups/")
        if info["version"] > memmod.LATEST:
            return Check(FAIL, f"database schema v{info['version']} is newer than supported v{memmod.LATEST}")
        if info["version"] < memmod.LATEST or info["missing"]:
            why = f"schema v{info['version']} -> v{memmod.LATEST}" if info["version"] < memmod.LATEST else \
                "missing tables: " + ", ".join(info["missing"])
            return Check(ACTION, f"database needs migration ({why})", "Back up and migrate database?",
                         "Migrating memory (backup first)...", fix_old, "Memory migrated")
        return Check(PASS, f"schema v{info['version']}, existing data preserved")

    # ----- stage 9 -----
    def c_agents(self):
        cfg = self.cfg
        prob = registry_problem(cfg)
        agents = ", ".join(f"{n} {s}" for n, s in agent_list(cfg))
        if prob:
            return Check(ACTION, prob, "Write agent registry?", "Registering agents...",
                         lambda: write_registry(cfg), agents)
        return Check(PASS, agents)

    # ----- stage 10 -----
    def validate_skills(self):
        cfg, reg, errs = self.cfg, Registry(self.cfg), []
        for s in reg.skills.values():
            if s.perm != Perm.READ_ONLY:
                errs.append(f"{s.name}: not READ_ONLY")
        try:
            reg.run("read_text_file", "/etc/passwd")
            errs.append("read_text_file: path restriction not enforced")
        except PermissionDenied:
            pass
        except Exception:
            pass
        calls = [("system_info",), ("memory_info",), ("disk_info",), ("git_status", cfg.root),
                 ("list_directory", cfg.root if os.path.isdir(cfg.root) else ".")]
        for c in calls:
            try:
                if not reg.run(*c):
                    errs.append(f"{c[0]}: empty result")
            except Exception as e:
                errs.append(f"{c[0]}: {e.__class__.__name__}")
        return reg, errs

    def c_skills(self):
        cfg = self.cfg
        reg, errs = self.validate_skills()
        if errs:
            return Check(FAIL, "; ".join(errs)[:200])
        info = memmod.inspect(cfg.path("memory", "savage.db"))
        have = set(info.get("skills", []))
        miss = [n for n in reg.names() if n not in have]
        if miss:
            def fix():
                m = memmod.Memory(cfg)
                try:
                    Registry(cfg, m).sync()
                finally:
                    m.close()
            return Check(ACTION, f"{len(miss)} built-in skills not registered", "Register built-in READ_ONLY skills?",
                         "Registering skills...", fix, f"{len(reg.names())} READ_ONLY skills registered")
        return Check(PASS, f"{len(reg.names())} READ_ONLY skills registered and validated")

    # ----- stage 11 -----
    def c_inference(self):
        s = LlamaCppProvider(self.cfg).status()
        self.extra = [("llama.cpp", PASS if s["executable_present"] else OPTIONAL,
                       "READY" if s["executable_present"] else "NOT INSTALLED"),
                      ("Local model", PASS if s["model_present"] else OPTIONAL,
                       "READY" if s["model_present"] else "NOT INSTALLED")]
        for n, st, d in self.extra:
            self.line(st, f"{n}: {d}")

    # ----- stage 12 -----
    def selftest(self):
        cfg, res = self.cfg, []

        def t(name, fn):
            try:
                res.append((name, True, fn() or ""))
            except Exception as e:
                res.append((name, False, f"{e.__class__.__name__}: {e}"))

        def t_config():
            c = Config(root=cfg.root, env=cfg.env)
            assert c.get("context_size") > 0

        def t_sql():
            info = memmod.inspect(cfg.path("memory", "savage.db"))
            assert "error" not in info and info["exists"], "database not readable"

        def t_mem():
            if self.check:
                return "skipped (--check writes nothing)"
            sid, m = "selftest-" + uuid.uuid4().hex[:8], memmod.Memory(cfg)
            try:
                m.db.execute("INSERT INTO sessions VALUES(?,?,?)", (sid, time.time(), time.time()))
                m.add_message(sid, "user", "selftest")
                assert m.history(sid)[0][3] == "selftest", "read-back mismatch"
            finally:
                m.delete_session(sid)
                m.close()

        def t_cmd():
            c = Commander(cfg, None, Registry(cfg))
            assert isinstance(c.provider_status(), list)

        def t_perm():
            perm_check(Perm.READ_ONLY, "SAFE")
            for p in (Perm.LOCAL, Perm.NETWORK, Perm.PRIVILEGED, Perm.TARGET_AFFECTING):
                try:
                    perm_check(p, "SAFE")
                except PermissionDenied:
                    continue
                raise AssertionError(f"{p.name} allowed in SAFE mode")

        def t_launcher():
            env = dict(os.environ, SAVAGE_AI_ROOT=cfg.root, PYTHONDONTWRITEBYTECODE="1")
            p = subprocess.run([cfg.path("bin", "savage"), "version"], capture_output=True, text=True,
                               timeout=30, env=env)
            assert p.returncode == 0 and p.stdout.strip() == __version__, (p.stdout + p.stderr)[:120]

        def t_dirs():
            for d in ("tmp", "logs", "memory"):
                assert os.access(cfg.path(d), os.R_OK | os.W_OK), f"{d}/ not accessible"
            if not self.check:
                p = cfg.path("tmp", f".selftest-{uuid.uuid4().hex[:6]}")
                with open(p, "w") as f:
                    f.write("x")
                with open(p) as f:
                    assert f.read() == "x"
                os.unlink(p)

        for n, f in (("configuration load", t_config), ("SQLite connection", t_sql),
                     ("memory write/read", t_mem), ("Commander init", t_cmd), ("skill registry", None),
                     ("permission system", t_perm), ("CLI launcher", t_launcher), ("runtime directories", t_dirs)):
            if f is None:
                t(n, lambda: None if not self.validate_skills()[1] else (_ for _ in ()).throw(AssertionError("skill error")))
            else:
                t(n, f)
        bad = [(n, d) for n, ok, d in res if not ok]
        for n, ok, d in res:
            self.v(f"{n}: {'ok' if ok else 'FAILED'} {d}")
        if bad:
            return Check(FAIL, "; ".join(f"{n}: {d}" for n, d in bad)[:200])
        return Check(PASS, f"{len(res)} tests passed" + (" (read-only subset)" if self.check else ""))

    # ----- run -----
    def run(self):
        cfg = self.cfg
        self.extra = []
        self.p("SAVAGE DOCTOR" + (" (check only - nothing will be changed)" if self.check else ""))
        self.p(f"Root: {cfg.root}")
        self.stage("platform", "Platform", self.c_platform)
        self.stage("storage", "Savage storage", self.c_storage)
        if self.res("storage") != PASS:
            return self.report()
        self.state = State(cfg)
        if os.path.isdir(cfg.path("logs")):
            self.attach_log()
        self.stage("dirs", "Directories", self.c_dirs)
        if self.fatal or (self.res("dirs") != PASS and not self.check):
            return self.report()
        self.attach_log()
        self.stage("python", "Python", self.c_python)
        self.stage("app", "Application", self.c_app)
        self.stage("launcher", "CLI launcher", self.c_launcher)
        self.stage("config", "Configuration", self.c_config)
        self.stage("memory", "Memory", self.c_memory)
        self.stage("agents", "Agents", self.c_agents)
        self.stage("skills", "Skills", self.c_skills)
        self.c_inference()
        core_ok = all(self.res(k) == PASS for k in ("python", "app", "launcher", "config", "memory", "agents", "skills"))
        if core_ok:
            self.stage("selftest", "Self test", self.selftest)
        else:
            self.line(OPTIONAL, "Self test: skipped (earlier stages not complete)")
            self.results.append(("selftest", "Self test", OPTIONAL, "skipped"))
        return self.report()

    def report(self):
        self.p()
        self.p("SAVAGE DOCTOR")
        words = {PASS: "PASS", ACTION: "ACTION NEEDED", FAIL: "FAILED", OPTIONAL: "SKIPPED"}
        for k, label, s, _ in self.results:
            self.p(f"{label:<18}{words[s]}")
        done = {k for k, *_ in self.results}
        for k, label in (("dirs", "Directories"), ("python", "Python"), ("app", "Application")):
            if k not in done:
                self.p(f"{label:<18}NOT RUN")
        if "selftest" in done:
            self.p(f"{'Commander':<18}{words[self.res('selftest')]}")
        if "agents" in done:
            op = dict(agent_list(self.cfg))["Operator"]
            self.p(f"{'Operator':<18}{op}")
        for n, s, d in self.extra:
            self.p(f"{n:<18}{d}")
        core_keys = ("platform", "storage", "dirs", "python", "app", "launcher", "config", "memory", "agents", "skills", "selftest")
        ready = all(self.res(k) == PASS for k in core_keys)
        self.p()
        if ready:
            self.p("CORE SYSTEM READY" + ("" if not self.check else " (read-only check)"))
            self.p("Run: savage")
            return 0
        if self.fatal and self.res("storage") != PASS:
            self.p("CORE SYSTEM NOT READY - fix storage first (see above)")
            return 2
        self.p("CORE SYSTEM NOT READY - run `savage doctor`" + (" (add --yes for safe repairs)" if self.check else " again after fixing the above"))
        return 1


def main(cfg, check=False, yes=False, verbose=False, inp=input, out=None, prefix=None):
    if check and yes:
        print("--check is read-only; ignoring --yes", file=out or sys.stdout)
        yes = False
    return Doctor(cfg, check, yes, verbose, inp, out, prefix).run()
